# Generated by Django 5.0 on 2023-12-08 19:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mainpagetable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ModelNo', models.CharField(max_length=100)),
                ('VendorType', models.CharField(max_length=100)),
                ('CompanyType', models.CharField(max_length=100)),
                ('ItemType', models.CharField(max_length=100)),
                ('HSNCode', models.CharField(max_length=100)),
                ('PriceFromChina', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('DeclaredCustomPrice', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('SellingPrice', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('DateTime', models.DateTimeField()),
            ],
            options={
                'unique_together': {('ModelNo', 'VendorType')},
            },
        ),
    ]
